#:kivy 1.10.1

<MainWidget>:

    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Line:
            width: 1.
            rectangle: (125, 25, self.width - 155, self.height - 55)

    Label:
        font_size: 100
        center_x: root.width / 16
        top: root.top - 50
        text: str(root.current)

    Label:
        font_size: 20
        center_x: root.width / 2 + 70
        top: 100
        text: root.path